---
- name: ensure unattended-upgrades package is installed
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 600
  with_items:
    - unattended-upgrades

- name: update apt configuration from templates
  template:
    src: etc/apt/apt.conf.d/{{ item }}
    dest: /etc/apt/apt.conf.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades

- name: upgrade software packages to latest version
  apt:
    upgrade: dist
    autoremove: true
    purge: true
    update_cache: true
    cache_valid_time: 600

- name: register installed kernel version
  shell: dpkg -l | grep "linux-image-[0-9]" | sort | tail -1 | perl -lane 'print substr($F[1], 12)'
  register: upgrade_query_installed_kernel
  changed_when: false

- include: reboot.yml
  when: upgrade_enable_reboot_on_kernel_change and
        upgrade_query_installed_kernel.stdout != ansible_kernel
