---
- name: reboot the machine
  shell: sleep 5 && /sbin/reboot
  async: 1
  poll: 0
  ignore_errors: yes

- name: wait for ssh to come back up after reboot
  become: false
  delegate_to: localhost
  wait_for:
    host: "{{ ansible_host|default(ansible_ssh_host|default(inventory_hostname)) }}"
    port: "{{ ansible_port|default(ansible_ssh_port|default(22)) }}"
    delay: 30
    timeout: 600
    state: started
